// Generated by scripts/scrape-site.mjs from https://www.stahovanie-jptransport.sk/
export const cityLinks = [
  {
    "href": "/stahovanie-banovce-nad-bebravou.html",
    "label": "Sťahovanie Bánovce nad Bebravou"
  },
  {
    "href": "/stahovanie-banska-bystrica.html",
    "label": "Sťahovanie Banská Bystrica"
  },
  {
    "href": "/stahovanie-banska-stiavnica.html",
    "label": "Sťahovanie Banská Štiavnica"
  },
  {
    "href": "/stahovanie-bardejov.html",
    "label": "Sťahovanie Bardejov"
  },
  {
    "href": "/stahovanie-bratislava.html",
    "label": "Sťahovanie Bratislava"
  },
  {
    "href": "/stahovanie-brezno.html",
    "label": "Sťahovanie Brezno"
  },
  {
    "href": "/stahovanie-bytca.html",
    "label": "Sťahovanie Bytča"
  },
  {
    "href": "/stahovanie-cadca.html",
    "label": "Sťahovanie Čadca"
  },
  {
    "href": "/stahovanie-detva.html",
    "label": "Sťahovanie Detva"
  },
  {
    "href": "/stahovanie-dolny-kubin.html",
    "label": "Sťahovanie Dolný Kubín"
  },
  {
    "href": "/stahovanie-dubnica-nad-vahom.html",
    "label": "Sťahovanie Dubnica nad Váhom"
  },
  {
    "href": "/stahovanie-dunajska-streda.html",
    "label": "Sťahovanie Dunajská Streda"
  },
  {
    "href": "/stahovanie-filakovo.html",
    "label": "Sťahovanie Fiľakovo"
  },
  {
    "href": "/stahovanie-galanta.html",
    "label": "Sťahovanie Galanta"
  },
  {
    "href": "/stahovanie-handlova.html",
    "label": "Sťahovanie Handlová"
  },
  {
    "href": "/stahovanie-hlohovec.html",
    "label": "Sťahovanie Hlohovec"
  },
  {
    "href": "/stahovanie-hnusta.html",
    "label": "Sťahovanie Hnúšťa"
  },
  {
    "href": "/stahovanie-holic.html",
    "label": "Sťahovanie Holíč"
  },
  {
    "href": "/stahovanie-hrinova.html",
    "label": "Sťahovanie Hriňová"
  },
  {
    "href": "/stahovanie-humenne.html",
    "label": "Sťahovanie Humenné"
  },
  {
    "href": "/stahovanie-hurbanovo.html",
    "label": "Sťahovanie Hurbanovo"
  },
  {
    "href": "/stahovanie-ilava.html",
    "label": "Sťahovanie Ilava"
  },
  {
    "href": "/stahovanie-kezmarok.html",
    "label": "Sťahovanie Kežmarok"
  },
  {
    "href": "/stahovanie-kolarovo.html",
    "label": "Sťahovanie Kolárovo"
  },
  {
    "href": "/stahovanie-komarno.html",
    "label": "Sťahovanie Komárno"
  },
  {
    "href": "/stahovanie-kosice.html",
    "label": "Sťahovanie Košice"
  },
  {
    "href": "/stahovanie-kralovsky-chlmec.html",
    "label": "Sťahovanie Kráľovský Chlmec"
  },
  {
    "href": "/stahovanie-krasno-nad-kysucou.html",
    "label": "Sťahovanie Krásno nad Kysucou"
  },
  {
    "href": "/stahovanie-krompachy.html",
    "label": "Sťahovanie Krompachy"
  },
  {
    "href": "/stahovanie-krupina.html",
    "label": "Sťahovanie Krupina"
  },
  {
    "href": "/stahovanie-kysucke-nove-mesto.html",
    "label": "Sťahovanie Kysucké Nové Mesto"
  },
  {
    "href": "/stahovanie-levice.html",
    "label": "Sťahovanie Levice"
  },
  {
    "href": "/stahovanie-levoca.html",
    "label": "Sťahovanie Levoča"
  },
  {
    "href": "/stahovanie-lipany.html",
    "label": "Sťahovanie Lipany"
  },
  {
    "href": "/stahovanie-liptovsky-hradok.html",
    "label": "Sťahovanie Liptovský Hrádok"
  },
  {
    "href": "/stahovanie-liptovsky-mikulas.html",
    "label": "Sťahovanie Liptovský Mikuláš"
  },
  {
    "href": "/stahovanie-malacky.html",
    "label": "Sťahovanie Malacky"
  },
  {
    "href": "/stahovanie-martin.html",
    "label": "Sťahovanie Martin"
  },
  {
    "href": "/stahovanie-michalovce.html",
    "label": "Sťahovanie Michalovce"
  },
  {
    "href": "/stahovanie-modra.html",
    "label": "Sťahovanie Modra"
  },
  {
    "href": "/stahovanie-moldava-nad-bodvou.html",
    "label": "Sťahovanie Moldava nad Bodvou"
  },
  {
    "href": "/stahovanie-myjava.html",
    "label": "Sťahovanie Myjava"
  },
  {
    "href": "/stahovanie-namestovo.html",
    "label": "Sťahovanie Námestovo"
  },
  {
    "href": "/stahovanie-nitra.html",
    "label": "Sťahovanie Nitra"
  },
  {
    "href": "/stahovanie-nova-bana.html",
    "label": "Sťahovanie Nová Baňa"
  },
  {
    "href": "/stahovanie-nova-dubnica.html",
    "label": "Sťahovanie Nová Dubnica"
  },
  {
    "href": "/stahovanie-nove-mesto-nad-vahom.html",
    "label": "Sťahovanie Nové Mesto nad Váhom"
  },
  {
    "href": "/stahovanie-nove-zamky.html",
    "label": "Sťahovanie Nové Zámky"
  },
  {
    "href": "/stahovanie-partizanske.html",
    "label": "Sťahovanie Partizánske"
  },
  {
    "href": "/stahovanie-pezinok.html",
    "label": "Sťahovanie Pezinok"
  },
  {
    "href": "/stahovanie-piestany.html",
    "label": "Sťahovanie Piešťany"
  },
  {
    "href": "/stahovanie-poprad.html",
    "label": "Sťahovanie Poprad"
  },
  {
    "href": "/stahovanie-povazska-bystrica.html",
    "label": "Sťahovanie Považská Bystrica"
  },
  {
    "href": "/stahovanie-presov.html",
    "label": "Sťahovanie Prešov"
  },
  {
    "href": "/stahovanie-prievidza.html",
    "label": "Sťahovanie Prievidza"
  },
  {
    "href": "/stahovanie-puchov.html",
    "label": "Sťahovanie Púchov"
  },
  {
    "href": "/stahovanie-revuca.html",
    "label": "Sťahovanie Revúca"
  },
  {
    "href": "/stahovanie-rimavska-sobota.html",
    "label": "Sťahovanie Rimavská Sobota"
  },
  {
    "href": "/stahovanie-roznava.html",
    "label": "Sťahovanie Rožňava"
  },
  {
    "href": "/stahovanie-ruzomberok.html",
    "label": "Sťahovanie Ružomberok"
  },
  {
    "href": "/stahovanie-sabinov.html",
    "label": "Sťahovanie Sabinov"
  },
  {
    "href": "/stahovanie-secovce.html",
    "label": "Sťahovanie Sečovce"
  },
  {
    "href": "/stahovanie-senec.html",
    "label": "Sťahovanie Senec"
  },
  {
    "href": "/stahovanie-senica.html",
    "label": "Sťahovanie Senica"
  },
  {
    "href": "/stahovanie-sered.html",
    "label": "Sťahovanie Sereď"
  },
  {
    "href": "/stahovanie-skalica.html",
    "label": "Sťahovanie Skalica"
  },
  {
    "href": "/stahovanie-snina.html",
    "label": "Sťahovanie Snina"
  },
  {
    "href": "/stahovanie-spisska-bela.html",
    "label": "Sťahovanie Spišská Belá"
  },
  {
    "href": "/stahovanie-spisska-nova-ves.html",
    "label": "Sťahovanie Spišská Nová Ves"
  },
  {
    "href": "/stahovanie-stara-lubovna.html",
    "label": "Sťahovanie Stará Ľubovňa"
  },
  {
    "href": "/stahovanie-stropkov.html",
    "label": "Sťahovanie Stropkov"
  },
  {
    "href": "/stahovanie-stupava.html",
    "label": "Sťahovanie Stupava"
  },
  {
    "href": "/stahovanie-svidnik.html",
    "label": "Sťahovanie Svidník"
  },
  {
    "href": "/stahovanie-svit.html",
    "label": "Sťahovanie Svit"
  },
  {
    "href": "/stahovanie-sahy.html",
    "label": "Sťahovanie Šahy"
  },
  {
    "href": "/stahovanie-sala.html",
    "label": "Sťahovanie Šaľa"
  },
  {
    "href": "/stahovanie-samorin.html",
    "label": "Sťahovanie Šamorín"
  },
  {
    "href": "/stahovanie-sturovo.html",
    "label": "Sťahovanie Štúrovo"
  },
  {
    "href": "/stahovanie-surany.html",
    "label": "Sťahovanie Šurany"
  },
  {
    "href": "/stahovanie-topolcany.html",
    "label": "Sťahovanie Topoľčany"
  },
  {
    "href": "/stahovanie-tornala.html",
    "label": "Sťahovanie Tornaľa"
  },
  {
    "href": "/stahovanie-trebisov.html",
    "label": "Sťahovanie Trebišov"
  },
  {
    "href": "/stahovanie-trencin.html",
    "label": "Sťahovanie Trenčín"
  },
  {
    "href": "/stahovanie-trnava.html",
    "label": "Sťahovanie Trnava"
  },
  {
    "href": "/stahovanie-trstena.html",
    "label": "Sťahovanie Trstená"
  },
  {
    "href": "/stahovanie-turzovka.html",
    "label": "Sťahovanie Turzovka"
  },
  {
    "href": "/stahovanie-tvrdosin.html",
    "label": "Sťahovanie Tvrdošín"
  },
  {
    "href": "/stahovanie-velke-kapusany.html",
    "label": "Sťahovanie Veľké Kapušany"
  },
  {
    "href": "/stahovanie-velky-krtis.html",
    "label": "Sťahovanie Veľký Krtíš"
  },
  {
    "href": "/stahovanie-velky-meder.html",
    "label": "Sťahovanie Veľký Meder"
  },
  {
    "href": "/stahovanie-velky-saris.html",
    "label": "Sťahovanie Veľký Šariš"
  },
  {
    "href": "/stahovanie-vrable.html",
    "label": "Sťahovanie Vráble"
  },
  {
    "href": "/stahovanie-vrutky.html",
    "label": "Sťahovanie Vrútky"
  },
  {
    "href": "/stahovanie-zlate-moravce.html",
    "label": "Sťahovanie Zlaté Moravce"
  },
  {
    "href": "/stahovanie-zvolen.html",
    "label": "Sťahovanie Zvolen"
  },
  {
    "href": "/stahovanie-zeliezovce.html",
    "label": "Sťahovanie Želiezovce"
  },
  {
    "href": "/stahovanie-ziar-nad-hronom.html",
    "label": "Sťahovanie Žiar nad Hronom"
  },
  {
    "href": "/stahovanie-zilina.html",
    "label": "Sťahovanie Žilina"
  }
] as const;
export const priceLinks = [
  {
    "href": "/cennik-stahovanie-banovce-nad-bebravou.html",
    "label": "Cenník sťahovania Bánovce nad Bebravou"
  },
  {
    "href": "/cennik-stahovanie-banska-bystrica.html",
    "label": "Cenník sťahovania Banská Bystrica"
  },
  {
    "href": "/cennik-stahovanie-bardejov.html",
    "label": "Cenník sťahovania Bardejov"
  },
  {
    "href": "/cennik-stahovanie-bratislava.html",
    "label": "Cenník sťahovania Bratislava"
  },
  {
    "href": "/cennik-stahovanie-brezno.html",
    "label": "Cenník sťahovania Brezno"
  },
  {
    "href": "/cennik-stahovanie-bytca.html",
    "label": "Cenník sťahovania Bytča"
  },
  {
    "href": "/cennik-stahovanie-cadca.html",
    "label": "Cenník sťahovania Čadca"
  },
  {
    "href": "/cennik-stahovanie-detva.html",
    "label": "Cenník sťahovania Detva"
  },
  {
    "href": "/cennik-stahovanie-dolny-kubin.html",
    "label": "Cenník sťahovania Dolný Kubín"
  },
  {
    "href": "/cennik-stahovanie-dubnica-nad-vahom.html",
    "label": "Cenník sťahovania Dubnica nad Váhom"
  },
  {
    "href": "/cennik-stahovanie-dunajska-streda.html",
    "label": "Cenník sťahovania Dunajská Streda"
  },
  {
    "href": "/cennik-stahovanie-filakovo.html",
    "label": "Cenník sťahovania Fiľakovo"
  },
  {
    "href": "/cennik-stahovanie-galanta.html",
    "label": "Cenník sťahovania Galanta"
  },
  {
    "href": "/cennik-stahovanie-handlova.html",
    "label": "Cenník sťahovania Handlová"
  },
  {
    "href": "/cennik-stahovanie-hlohovec.html",
    "label": "Cenník sťahovania Hlohovec"
  },
  {
    "href": "/cennik-stahovanie-hnusta.html",
    "label": "Cenník sťahovania Hnúšťa"
  },
  {
    "href": "/cennik-stahovanie-holic.html",
    "label": "Cenník sťahovania Holíč"
  },
  {
    "href": "/cennik-stahovanie-hrinova.html",
    "label": "Cenník sťahovania Hriňová"
  },
  {
    "href": "/cennik-stahovanie-humenne.html",
    "label": "Cenník sťahovania Humenné"
  },
  {
    "href": "/cennik-stahovanie-hurbanovo.html",
    "label": "Cenník sťahovania Hurbanovo"
  },
  {
    "href": "/cennik-stahovanie-kezmarok.html",
    "label": "Cenník sťahovania Kežmarok"
  },
  {
    "href": "/cennik-stahovanie-kolarovo.html",
    "label": "Cenník sťahovania Kolárovo"
  },
  {
    "href": "/cennik-stahovanie-komarno.html",
    "label": "Cenník sťahovania Komárno"
  },
  {
    "href": "/cennik-stahovanie-kosice.html",
    "label": "Cenník sťahovania Košice"
  },
  {
    "href": "/cennik-stahovanie-kralovsky-chlmec.html",
    "label": "Cenník sťahovania Kráľovský Chlmec"
  },
  {
    "href": "/cennik-stahovanie-krasno-nad-kysucou.html",
    "label": "Cenník sťahovania Krásno nad Kysucou"
  },
  {
    "href": "/cennik-stahovanie-krompachy.html",
    "label": "Cenník sťahovania Krompachy"
  },
  {
    "href": "/cennik-stahovanie-krupina.html",
    "label": "Cenník sťahovania Krupina"
  },
  {
    "href": "/cennik-stahovanie-kysucke-nove-mesto.html",
    "label": "Cenník sťahovania Kysucké Nové Mesto"
  },
  {
    "href": "/cennik-stahovanie-levice.html",
    "label": "Cenník sťahovania Levice"
  },
  {
    "href": "/cennik-stahovanie-levoca.html",
    "label": "Cenník sťahovania Levoča"
  },
  {
    "href": "/cennik-stahovanie-lipany.html",
    "label": "Cenník sťahovania Lipany"
  },
  {
    "href": "/cennik-stahovanie-liptovsky-hradok.html",
    "label": "Cenník sťahovania Liptovský Hrádok"
  },
  {
    "href": "/cennik-stahovanie-liptovsky-mikulas.html",
    "label": "Cenník sťahovania Liptovský Mikuláš"
  },
  {
    "href": "/cennik-stahovanie-malacky.html",
    "label": "Cenník sťahovania Malacky"
  },
  {
    "href": "/cennik-stahovanie-martin.html",
    "label": "Cenník sťahovania Martin"
  },
  {
    "href": "/cennik-stahovanie-michalovce.html",
    "label": "Cenník sťahovania Michalovce"
  },
  {
    "href": "/cennik-stahovanie-modra.html",
    "label": "Cenník sťahovania Modra"
  },
  {
    "href": "/cennik-stahovanie-moldava-nad-bodvou.html",
    "label": "Cenník sťahovania Moldava nad Bodvou"
  },
  {
    "href": "/cennik-stahovanie-myjava.html",
    "label": "Cenník sťahovania Myjava"
  },
  {
    "href": "/cennik-stahovanie-namestovo.html",
    "label": "Cenník sťahovania Námestovo"
  },
  {
    "href": "/cennik-stahovanie-nitra.html",
    "label": "Cenník sťahovania Nitra"
  },
  {
    "href": "/cennik-stahovanie-nova-bana.html",
    "label": "Cenník sťahovania Nová Baňa"
  },
  {
    "href": "/cennik-stahovanie-nova-dubnica.html",
    "label": "Cenník sťahovania Nová Dubnica"
  },
  {
    "href": "/cennik-stahovanie-nove-mesto-nad-vahom.html",
    "label": "Cenník sťahovania Nové Mesto nad Váhom"
  },
  {
    "href": "/cennik-stahovanie-nove-zamky.html",
    "label": "Cenník sťahovania Nové Zámky"
  },
  {
    "href": "/cennik-stahovanie-partizanske.html",
    "label": "Cenník sťahovania Partizánske"
  },
  {
    "href": "/cennik-stahovanie-pezinok.html",
    "label": "Cenník sťahovania Pezinok"
  },
  {
    "href": "/cennik-stahovanie-piestany.html",
    "label": "Cenník sťahovania Piešťany"
  },
  {
    "href": "/cennik-stahovanie-poprad.html",
    "label": "Cenník sťahovania Poprad"
  },
  {
    "href": "/cennik-stahovanie-povazska-bystrica.html",
    "label": "Cenník sťahovania Považská Bystrica"
  },
  {
    "href": "/cennik-stahovanie-presov.html",
    "label": "Cenník sťahovania Prešov"
  },
  {
    "href": "/cennik-stahovanie-prievidza.html",
    "label": "Cenník sťahovania Prievidza"
  },
  {
    "href": "/cennik-stahovanie-puchov.html",
    "label": "Cenník sťahovania Púchov"
  },
  {
    "href": "/cennik-stahovanie-revuca.html",
    "label": "Cenník sťahovania Revúca"
  },
  {
    "href": "/cennik-stahovanie-rimavska-sobota.html",
    "label": "Cenník sťahovania Rimavská Sobota"
  },
  {
    "href": "/cennik-stahovanie-roznava.html",
    "label": "Cenník sťahovania Rožňava"
  },
  {
    "href": "/cennik-stahovanie-ruzomberok.html",
    "label": "Cenník sťahovania Ružomberok"
  },
  {
    "href": "/cennik-stahovanie-sabinov.html",
    "label": "Cenník sťahovania Sabinov"
  },
  {
    "href": "/cennik-stahovanie-secovce.html",
    "label": "Cenník sťahovania Sečovce"
  },
  {
    "href": "/cennik-stahovanie-senec.html",
    "label": "Cenník sťahovania Senec"
  },
  {
    "href": "/cennik-stahovanie-senica.html",
    "label": "Cenník sťahovania Senica"
  },
  {
    "href": "/cennik-stahovanie-sered.html",
    "label": "Cenník sťahovania Sereď"
  },
  {
    "href": "/cennik-stahovanie-skalica.html",
    "label": "Cenník sťahovania Skalica"
  },
  {
    "href": "/cennik-stahovanie-snina.html",
    "label": "Cenník sťahovania Snina"
  },
  {
    "href": "/cennik-stahovanie-spisska-bela.html",
    "label": "Cenník sťahovania Spišská Belá"
  },
  {
    "href": "/cennik-stahovanie-spisska-nova-ves.html",
    "label": "Cenník sťahovania Spišská Nová Ves"
  },
  {
    "href": "/cennik-stahovanie-stara-lubovna.html",
    "label": "Cenník sťahovania Stará Ľubovňa"
  },
  {
    "href": "/cennik-stahovanie-stara-tura.html",
    "label": "Cenník sťahovania Stará Turá"
  },
  {
    "href": "/cennik-stahovanie-stropkov.html",
    "label": "Cenník sťahovania Stropkov"
  },
  {
    "href": "/cennik-stahovanie-stupava.html",
    "label": "Cenník sťahovania Stupava"
  },
  {
    "href": "/cennik-stahovanie-svidnik.html",
    "label": "Cenník sťahovania Svidník"
  },
  {
    "href": "/cennik-stahovanie-svit.html",
    "label": "Cenník sťahovania Svit"
  },
  {
    "href": "/cennik-stahovanie-sahy.html",
    "label": "Cenník sťahovania Šahy"
  },
  {
    "href": "/cennik-stahovanie-sala.html",
    "label": "Cenník sťahovania Šaľa"
  },
  {
    "href": "/cennik-stahovanie-samorin.html",
    "label": "Cenník sťahovania Šamorín"
  },
  {
    "href": "/cennik-stahovanie-sturovo.html",
    "label": "Cenník sťahovania Štúrovo"
  },
  {
    "href": "/cennik-stahovanie-surany.html",
    "label": "Cenník sťahovania Šurany"
  },
  {
    "href": "/cennik-stahovanie-topolcany.html",
    "label": "Cenník sťahovania Topoľčany"
  },
  {
    "href": "/cennik-stahovanie-tornala.html",
    "label": "Cenník sťahovania Tornaľa"
  },
  {
    "href": "/cennik-stahovanie-trebisov.html",
    "label": "Cenník sťahovania Trebišov"
  },
  {
    "href": "/cennik-stahovanie-trencin.html",
    "label": "Cenník sťahovania Trenčín"
  },
  {
    "href": "/cennik-stahovanie-trnava.html",
    "label": "Cenník sťahovania Trnava"
  },
  {
    "href": "/cennik-stahovanie-trstena.html",
    "label": "Cenník sťahovania Trstená"
  },
  {
    "href": "/cennik-stahovanie-turzovka.html",
    "label": "Cenník sťahovania Turzovka"
  },
  {
    "href": "/cennik-stahovanie-tvrdosin.html",
    "label": "Cenník sťahovania Tvrdošín"
  },
  {
    "href": "/cennik-stahovanie-velke-kapusany.html",
    "label": "Cenník sťahovania Veľké Kapušany"
  },
  {
    "href": "/cennik-stahovanie-velky-krtis.html",
    "label": "Cenník sťahovania Veľký Krtíš"
  },
  {
    "href": "/cennik-stahovanie-velky-meder.html",
    "label": "Cenník sťahovania Veľký Meder"
  },
  {
    "href": "/cennik-stahovanie-velky-saris.html",
    "label": "Cenník sťahovania Veľký Šariš"
  },
  {
    "href": "/cennik-stahovanie-vrable.html",
    "label": "Cenník sťahovania Vráble"
  },
  {
    "href": "/cennik-stahovanie-vranov-nad-toplou.html",
    "label": "Cenník sťahovania Vranov nad Topľou"
  },
  {
    "href": "/cennik-stahovanie-vrutky.html",
    "label": "Cenník sťahovania Vrútky"
  },
  {
    "href": "/cennik-stahovanie-zlate-moravce.html",
    "label": "Cenník sťahovania Zlaté Moravce"
  },
  {
    "href": "/cennik-stahovanie-zvolen.html",
    "label": "Cenník sťahovania Zvolen"
  },
  {
    "href": "/cennik-stahovanie-zeliezovce.html",
    "label": "Cenník sťahovania Želiezovce"
  },
  {
    "href": "/cennik-stahovanie-ziar-nad-hronom.html",
    "label": "Cenník sťahovania Žiar nad Hronom"
  },
  {
    "href": "/cennik-stahovanie-zilina.html",
    "label": "Cenník sťahovania Žilina"
  }
] as const;
export const blogArticleLinks = [
  {
    "href": "/blog-ako-sa-prestahovat-bez-stresu.html",
    "title": "10 tipov, ako sa presťahovať bez stresu",
    "description": "Objavte 10 praktických rád, ako zvládnuť sťahovanie bez stresu a chaosu. Sťahujte sa jednoducho a efektívne s JP TRANSPORT.",
    "image": "/source/IMG_0714.jpg"
  },
  {
    "href": "/blog-vyber-stahovacej-firmy.html",
    "title": "Ako si správne vybrať sťahovaciu firmu",
    "description": "Vybrať si dobrú sťahovaciu firmu môže rozhodnúť o tom, či sa presťahujete hladko alebo s nervami. Tu sú tipy, ako vybrať správne.",
    "image": "/source/IMG_0714.jpg"
  },
  {
    "href": "/blog-zbavte-sa-zbytocnosti.html",
    "title": "Zbavte sa zbytočností pred sťahovaním",
    "description": "Zbavte sa starých vecí pred sťahovaním a zjednodušte si život. Menej stresu, nižšie náklady a poriadok vo veciach. Prečítajte si naše tipy.",
    "image": "/source/IMG_0714.jpg"
  }
] as const;

export const primaryLinks = [
  { href: "/", label: "Domov" },
  { href: "/stahovanie-bytu.html", label: "Sťahovanie bytu" },
  { href: "/stahovanie-domu.html", label: "Sťahovanie domu" },
  { href: "/stahovanie-firmy.html", label: "Sťahovanie firmy" },
  { href: "/cennik-stahovania.html", label: "Cenník" },
  { href: "/stahovanie-europa.html", label: "Európa" },
  { href: "/blog.html", label: "Blog" },
  { href: "/#kontakt", label: "Kontakt" }
] as const;
